/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Titanium SDK
 * Copyright TiDev, Inc. 04/07/2022-Present
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 */
package ti.navigationmode;

import android.content.Context;
import android.content.res.Resources;

import androidx.annotation.NonNull;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.TiConfig;
import org.appcelerator.titanium.TiApplication;


@Kroll.module(name = "TiNavigationmode", id = "ti.navigationmode")
public class TiNavigationmodeModule extends KrollModule {

    /**
     * Classic three-button navigation (Back, Home, Recent Apps)
     */
    public static final int NAVIGATION_BAR_INTERACTION_MODE_THREE_BUTTON = 0;
    /**
     * Two-button navigation (Android P navigation mode: Back, combined Home and Recent Apps)
     */
    public static final int NAVIGATION_BAR_INTERACTION_MODE_TWO_BUTTON = 1;
    /**
     * Full screen gesture mode (introduced with Android Q)
     */
    public static final int NAVIGATION_BAR_INTERACTION_MODE_GESTURE = 2;
    // Standard Debugging variables
    private static final String LCAT = "TiNavigationmodeModule";
    private static final boolean DBG = TiConfig.LOGD;

    public TiNavigationmodeModule() {
        super();
    }

    @Kroll.onAppCreate
    public static void onAppCreate(TiApplication app) {
    }


    public static int getNavigationBarInteractionMode(@NonNull final Context context) {
        final Resources resources = context.getResources();
        final int resourceId = resources.getIdentifier("config_navBarInteractionMode", "integer", "android");
        return resourceId > 0 ? resources.getInteger(resourceId) : NAVIGATION_BAR_INTERACTION_MODE_THREE_BUTTON;
    }

    // Methods
    @Kroll.getProperty
    public int getNavigationMode() {
        return getNavigationBarInteractionMode(TiApplication.getAppCurrentActivity());
    }


}

